// This file is auto-generated by mockupPreviewPlugin.ts.
type ModuleMap = Record<string, () => Promise<Record<string, unknown>>>;
export const modules: ModuleMap = {
  "./components/mockups/algotrader-dashboard/AgentCommandCenter.tsx": () => import("../components/mockups/algotrader-dashboard/AgentCommandCenter.tsx"),
  "./components/mockups/algotrader-dashboard/PrecisionInstrument.tsx": () => import("../components/mockups/algotrader-dashboard/PrecisionInstrument.tsx"),
  "./components/mockups/algotrader-dashboard/RiskFirstDashboard.tsx": () => import("../components/mockups/algotrader-dashboard/RiskFirstDashboard.tsx")
};
